# Generated by Django 2.2.7 on 2020-02-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetWorkManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('path', models.URLField()),
                ('type', models.CharField(max_length=100)),
                ('labels', models.TextField()),
                ('num_node', models.IntegerField()),
                ('num_link', models.IntegerField()),
            ],
            options={
                'db_table': 'network_manager',
            },
        ),
    ]
