# Generated by Django 2.2.7 on 2020-03-09 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_auto_20200206_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkEntireStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('network', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analysis.NetWorkManager')),
            ],
            options={
                'db_table': 'entire_statistics',
            },
        ),
    ]
