# Generated by Django 2.2.7 on 2020-03-09 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_networkentirestatistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkmanager',
            name='labels_entirety',
        ),
    ]
